// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oejjsyftylqfuozldhwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lampzeWZ0eWxxZnVvemxkaHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDg1NjMsImV4cCI6MjA3MzkyNDU2M30.RjEcimIh0Ic7OLkzAf9VXYtUVDq0Eu3cXspclpbHRz0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});